From bb0068fa48f6572e26070a11592ab87cca3fd090 Mon Sep 17 00:00:00 2001
From: Sean Gillies <sean@mapbox.com>
Date: Tue, 15 Sep 2020 14:06:25 -0600
Subject: [PATCH] xfail tests of boundless reads with fill_value

These require GDAL 3.1.4 (not yet released) or equivalent patches.
---
 tests/test_boundless_read.py | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/tests/test_boundless_read.py b/tests/test_boundless_read.py
index 76f7c9e1..19580792 100644
--- a/tests/test_boundless_read.py
+++ b/tests/test_boundless_read.py
@@ -72,6 +72,7 @@ def test_boundless_mask_not_all_valid():
     assert masked.mask[-1, :].all()
 
 
+@pytest.mark.xfail(reason="fill_value requires GDAL 3.1.4 or equivalent patches")
 def test_boundless_fill_value():
     """Confirm resolution of issue #1471"""
     with rasterio.open("tests/data/red.tif") as src:
@@ -102,6 +103,7 @@ def test_boundless_mask_special():
     assert not mask[-1, :].any()
 
 
+@pytest.mark.xfail(reason="fill_value requires GDAL 3.1.4 or equivalent patches")
 def test_boundless_fill_value_overview_masks():
     """Confirm a more general resolution to issue #1471"""
     with rasterio.open("tests/data/cogeo.tif") as src:
@@ -109,6 +111,7 @@ def test_boundless_fill_value_overview_masks():
     assert (data[:, 0] == 5).all()
 
 
+@pytest.mark.xfail(reason="fill_value requires GDAL 3.1.4 or equivalent patches")
 def test_boundless_masked_fill_value_overview_masks():
     """Confirm a more general resolution to issue #1471"""
     with rasterio.open("tests/data/cogeo.tif") as src:
